package IGU;

import LOGICA.HistorialManagerSingleton;
import LOGICA.HistorialManager;
import java.awt.Toolkit;
import java.awt.Cursor;
import java.awt.Dimension;
import LOGICA.Panel_graficos;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class DASHBOARD1 extends javax.swing.JFrame {

    Clientes cl1;
    Habitaciones hab1;
    Reserva rsv1;
    Registro_Clientes pri;
    check_out out;
    Clientes clien;
    Login lg;
    check_in in;
    Acompañantes ac;

    /**
     * Creates new form PRINCIPAL1
     */
    public DASHBOARD1() throws SQLException {
        initComponents();
        Panel_graficos.obtenerEstadosHabitaciones(jPanel_grafica_hab);
        Panel_graficos.mostrarReservasActivas(jPanel_grafica_reservas);
        Panel_graficos.MostrarClientes(lbl_cl, lbl_cl_rv);
        Panel_graficos.mostrarCalendario(jPanel_calendario);
        iniciarActualizacionGrafico();

        check.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jlabel_Reserva2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jlabel_Habi.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jlabel_Admin.setCursor(new Cursor(Cursor.HAND_CURSOR));
        acompa.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jlabel_Salir.setCursor(new Cursor(Cursor.HAND_CURSOR));
        check_In.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabel_Regis.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }

    private void iniciarActualizacionGrafico() throws SQLException {
        // Mostrar el gráfico la primera vez
        Panel_graficos.obtenerEstadosHabitaciones(jPanel_grafica_hab);
        Panel_graficos.mostrarReservasActivas(jPanel_grafica_reservas);
        Panel_graficos.MostrarClientes(lbl_cl, lbl_cl_rv);

        // Crear un timer que actualiza cada 10 segundos (10000 milisegundos)
        int intervalo = 30000; // 30 segundos

        new javax.swing.Timer(intervalo, e -> {
            System.out.println("Actualizando gráfico de habitaciones...");
            Panel_graficos.obtenerEstadosHabitaciones(jPanel_grafica_hab);
            Panel_graficos.mostrarReservasActivas(jPanel_grafica_reservas);
            try {
                Panel_graficos.MostrarClientes(lbl_cl, lbl_cl_rv);
            } catch (SQLException ex) {
                Logger.getLogger(DASHBOARD1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }).start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel_grafica_hab = new javax.swing.JPanel();
        jPanel_grafica_reservas = new javax.swing.JPanel();
        jPanel_grafica_clientes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbl_cl_rv = new javax.swing.JLabel();
        lbl_cl = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel_calendario = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        check = new javax.swing.JLabel();
        jlabel_Salir = new javax.swing.JLabel();
        acompa = new javax.swing.JLabel();
        jlabel_Habi = new javax.swing.JLabel();
        jlabel_Reserva2 = new javax.swing.JLabel();
        jlabel_Admin = new javax.swing.JLabel();
        check_In = new javax.swing.JLabel();
        jLabel_Regis = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal-Hotel Resort");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel_grafica_hab.setPreferredSize(new java.awt.Dimension(350, 210));

        javax.swing.GroupLayout jPanel_grafica_habLayout = new javax.swing.GroupLayout(jPanel_grafica_hab);
        jPanel_grafica_hab.setLayout(jPanel_grafica_habLayout);
        jPanel_grafica_habLayout.setHorizontalGroup(
            jPanel_grafica_habLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel_grafica_habLayout.setVerticalGroup(
            jPanel_grafica_habLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel_grafica_reservas.setPreferredSize(new java.awt.Dimension(350, 210));

        javax.swing.GroupLayout jPanel_grafica_reservasLayout = new javax.swing.GroupLayout(jPanel_grafica_reservas);
        jPanel_grafica_reservas.setLayout(jPanel_grafica_reservasLayout);
        jPanel_grafica_reservasLayout.setHorizontalGroup(
            jPanel_grafica_reservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel_grafica_reservasLayout.setVerticalGroup(
            jPanel_grafica_reservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );

        jPanel_grafica_clientes.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_grafica_clientes.setPreferredSize(new java.awt.Dimension(210, 110));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/usuario_1.png"))); // NOI18N
        jLabel2.setText("Clientes:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/licencia-de-conducir.png"))); // NOI18N
        jLabel3.setText("En Reserva:");

        lbl_cl_rv.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_cl_rv.setText("cliente");

        lbl_cl.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        lbl_cl.setText("cliente");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Clientes");

        javax.swing.GroupLayout jPanel_grafica_clientesLayout = new javax.swing.GroupLayout(jPanel_grafica_clientes);
        jPanel_grafica_clientes.setLayout(jPanel_grafica_clientesLayout);
        jPanel_grafica_clientesLayout.setHorizontalGroup(
            jPanel_grafica_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_grafica_clientesLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel_grafica_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel_grafica_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_cl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_cl_rv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(jPanel_grafica_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_grafica_clientesLayout.setVerticalGroup(
            jPanel_grafica_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_grafica_clientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_grafica_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lbl_cl))
                .addGap(18, 18, 18)
                .addGroup(jPanel_grafica_clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lbl_cl_rv))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel_calendarioLayout = new javax.swing.GroupLayout(jPanel_calendario);
        jPanel_calendario.setLayout(jPanel_calendarioLayout);
        jPanel_calendarioLayout.setHorizontalGroup(
            jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );
        jPanel_calendarioLayout.setVerticalGroup(
            jPanel_calendarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_grafica_hab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_grafica_reservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_grafica_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel_calendario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel_grafica_hab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_grafica_reservas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel_grafica_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel_calendario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(65, 104, 163));

        jLabel7.setBackground(new java.awt.Color(51, 102, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/coral.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Bahia Coral");

        jLabel9.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hotel Resort ");

        check.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/impuesto.png"))); // NOI18N
        check.setText("Check Out");
        check.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkMouseClicked(evt);
            }
        });

        jlabel_Salir.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jlabel_Salir.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cerrar-sesion.png"))); // NOI18N
        jlabel_Salir.setText("Salir");
        jlabel_Salir.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jlabel_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_SalirMouseClicked(evt);
            }
        });

        acompa.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        acompa.setForeground(new java.awt.Color(255, 255, 255));
        acompa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/grupo (1).png"))); // NOI18N
        acompa.setText("Acompañantes");
        acompa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        acompa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acompaMouseClicked(evt);
            }
        });

        jlabel_Habi.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jlabel_Habi.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_Habi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cama-matrimonial.png"))); // NOI18N
        jlabel_Habi.setText("Habitaciones");
        jlabel_Habi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jlabel_Habi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_HabiMouseClicked(evt);
            }
        });

        jlabel_Reserva2.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jlabel_Reserva2.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_Reserva2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/reserva.png"))); // NOI18N
        jlabel_Reserva2.setText("Reservas");
        jlabel_Reserva2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jlabel_Reserva2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_Reserva2MouseClicked(evt);
            }
        });

        jlabel_Admin.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jlabel_Admin.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/administracion.png"))); // NOI18N
        jlabel_Admin.setText("Administración");
        jlabel_Admin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jlabel_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_AdminMouseClicked(evt);
            }
        });

        check_In.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        check_In.setForeground(new java.awt.Color(255, 255, 255));
        check_In.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/revisar.png"))); // NOI18N
        check_In.setText("Check In");
        check_In.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        check_In.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_InMouseClicked(evt);
            }
        });

        jLabel_Regis.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel_Regis.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Regis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/nueva-cuenta (1).png"))); // NOI18N
        jLabel_Regis.setText("Registro Clientes");
        jLabel_Regis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel_Regis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RegisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_In, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlabel_Reserva2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlabel_Habi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlabel_Salir)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel1))
                        .addComponent(acompa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlabel_Admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Regis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jlabel_Reserva2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(check_In, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jlabel_Habi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jlabel_Admin)
                .addGap(34, 34, 34)
                .addComponent(jLabel_Regis, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(acompa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jlabel_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel3.setBackground(new java.awt.Color(74, 136, 197));

        jLabel10.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("DASHBOARD");

        jLabel11.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("USER");
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseClicked
        // TODO add your handling code here:}
        out = new check_out();  // Pasa null como idHabitacion
        out.setVisible(true);

        out.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - out.getSize().width) / 2;
        int y = (pantalla.height - out.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        out.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Check out ");

    }//GEN-LAST:event_checkMouseClicked

    private void jlabel_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_SalirMouseClicked
        // TODO add your handling code here:
        this.dispose(); // Cierra solo el JFrame actual

    }//GEN-LAST:event_jlabel_SalirMouseClicked

    private void acompaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acompaMouseClicked
        // TODO add your handling code here:
        ac = new Acompañantes();
        ac.setVisible(true);

        ac.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - ac.getSize().width) / 2;
        int y = (pantalla.height - ac.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        ac.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Acompañantes");
    }//GEN-LAST:event_acompaMouseClicked

    private void jlabel_HabiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_HabiMouseClicked
        // TODO add your handling code here:
        hab1 = new Habitaciones();  // Pasa null como idHabitacion
        hab1.setVisible(true);

        hab1.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - hab1.getSize().width) / 2;
        int y = (pantalla.height - hab1.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        hab1.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Habitaciones ");
    }//GEN-LAST:event_jlabel_HabiMouseClicked

    private void jlabel_Reserva2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_Reserva2MouseClicked
        // TODO add your handling code here:

        rsv1 = new Reserva();
        rsv1.setVisible(true);

        rsv1.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - rsv1.getSize().width) / 2;
        int y = (pantalla.height - rsv1.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        rsv1.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Reservas");
    }//GEN-LAST:event_jlabel_Reserva2MouseClicked

    private void jlabel_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_AdminMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        lg = new Login();
        lg.setVisible(true);

        lg.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - lg.getSize().width) / 2;
        int y = (pantalla.height - lg.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        lg.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Reservas");
    }//GEN-LAST:event_jlabel_AdminMouseClicked

    private void check_InMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_InMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        in = new check_in();
        in.setVisible(true);

        in.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - in.getSize().width) / 2;
        int y = (pantalla.height - in.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        in.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Check In");
    }//GEN-LAST:event_check_InMouseClicked

    private void jLabel_RegisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        pri = new Registro_Clientes();
        pri.setVisible(true);

        pri.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - pri.getSize().width) / 2;
        int y = (pantalla.height - pri.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        pri.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Registro Clientes");

    }//GEN-LAST:event_jLabel_RegisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DASHBOARD1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new DASHBOARD1().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(DASHBOARD1.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acompa;
    private javax.swing.JLabel check;
    private javax.swing.JLabel check_In;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Regis;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_calendario;
    private javax.swing.JPanel jPanel_grafica_clientes;
    private javax.swing.JPanel jPanel_grafica_hab;
    private javax.swing.JPanel jPanel_grafica_reservas;
    private javax.swing.JLabel jlabel_Admin;
    private javax.swing.JLabel jlabel_Habi;
    private javax.swing.JLabel jlabel_Reserva2;
    private javax.swing.JLabel jlabel_Salir;
    private javax.swing.JLabel lbl_cl;
    private javax.swing.JLabel lbl_cl_rv;
    // End of variables declaration//GEN-END:variables
}
