package IGU;

import LOGICA.HistorialManagerSingleton;
import LOGICA.HistorialManager;
import java.awt.Toolkit;
import java.awt.Cursor;
import java.awt.Dimension;

public class PRINCIPAL1 extends javax.swing.JFrame {

    Clientes cl1;
    Habitaciones hab1;
    Reserva rsv1;
    Registro_Clientes pri;
    check_out out;
    Clientes clien;
    Login lg;
    check_in in;
    Acompañantes ac;

    /**
     * Creates new form PRINCIPAL1
     */
    public PRINCIPAL1() {
        initComponents();
        btn_clientes.setBorderPainted(false);
        btn_clientes.setContentAreaFilled(false);
        btn_clientes.setFocusPainted(false);
        btn_clientes.setOpaque(false);
        btn_clientes.setCursor(new Cursor(Cursor.HAND_CURSOR));
        //reserva
        reserva.setBorderPainted(false);
        reserva.setContentAreaFilled(false);
        reserva.setFocusPainted(false);
        reserva.setOpaque(false);
        reserva.setCursor(new Cursor(Cursor.HAND_CURSOR));
        //habitacion
        habitacion.setBorderPainted(false);
        habitacion.setContentAreaFilled(false);
        habitacion.setFocusPainted(false);
        habitacion.setOpaque(false);
        habitacion.setCursor(new Cursor(Cursor.HAND_CURSOR));
        //admin
        admin.setBorderPainted(false);
        admin.setContentAreaFilled(false);
        admin.setFocusPainted(false);
        admin.setOpaque(false);
        admin.setCursor(new Cursor(Cursor.HAND_CURSOR));
        //check
        check_out.setBorderPainted(false);
        check_out.setContentAreaFilled(false);
        check_out.setFocusPainted(false);
        check_out.setOpaque(false);
        check_out.setCursor(new Cursor(Cursor.HAND_CURSOR));
        //check in
        labelchek.setBorderPainted(false);
        labelchek.setContentAreaFilled(false);
        labelchek.setFocusPainted(false);
        labelchek.setOpaque(false);
        labelchek.setCursor(new Cursor(Cursor.HAND_CURSOR));
        //acompñantes
        label_acompañantes.setBorderPainted(false);
        label_acompañantes.setContentAreaFilled(false);
        label_acompañantes.setFocusPainted(false);
        label_acompañantes.setOpaque(false);
        label_acompañantes.setCursor(new Cursor(Cursor.HAND_CURSOR));
        
        check.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jlabel_Reserva2.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jlabel_Habi.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jlabel_Admin.setCursor(new Cursor(Cursor.HAND_CURSOR));
        acompa.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jlabel_Salir.setCursor(new Cursor(Cursor.HAND_CURSOR));
        check_In.setCursor(new Cursor(Cursor.HAND_CURSOR));
        jLabel_Regis.setCursor(new Cursor(Cursor.HAND_CURSOR));
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        reserva = new javax.swing.JButton();
        btn_clientes = new javax.swing.JButton();
        admin = new javax.swing.JButton();
        habitacion = new javax.swing.JButton();
        check_out = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_acompañantes = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        labelchek = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        check = new javax.swing.JLabel();
        jlabel_Salir = new javax.swing.JLabel();
        acompa = new javax.swing.JLabel();
        jlabel_Habi = new javax.swing.JLabel();
        jlabel_Reserva2 = new javax.swing.JLabel();
        jlabel_Admin = new javax.swing.JLabel();
        check_In = new javax.swing.JLabel();
        jLabel_Regis = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Principal-Hotel Resort");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(65, 104, 163));
        jLabel2.setText("REGISTRO CLIENTES");

        reserva.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/calendario (2).png"))); // NOI18N
        reserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservaActionPerformed(evt);
            }
        });

        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/clientesadd.png"))); // NOI18N
        btn_clientes.setBorder(null);
        btn_clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_clientesMouseClicked(evt);
            }
        });
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });

        admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/gestion (1).png"))); // NOI18N
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        habitacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/reserva-en-linea.png"))); // NOI18N
        habitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                habitacionActionPerformed(evt);
            }
        });

        check_out.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/presupuesto.png"))); // NOI18N
        check_out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_outActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Georgia", 3, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(65, 104, 163));
        jLabel10.setText("MENU PRINCIPAL");

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(65, 104, 163));
        jLabel3.setText("RESERVAS");

        jLabel4.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(65, 104, 163));
        jLabel4.setText("CHECK IN");

        jLabel5.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(65, 104, 163));
        jLabel5.setText("CHECK OUT");

        jLabel6.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(65, 104, 163));
        jLabel6.setText("ADMINISTRACION");

        label_acompañantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/grupo.png"))); // NOI18N
        label_acompañantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                label_acompañantesMouseClicked(evt);
            }
        });
        label_acompañantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                label_acompañantesActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(65, 104, 163));
        jLabel11.setText("ACOMPAÑANTES");

        jLabel12.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(65, 104, 163));
        jLabel12.setText("HABITACIONES");

        labelchek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/tarjeta-clave (1).png"))); // NOI18N
        labelchek.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                labelchekMouseClicked(evt);
            }
        });
        labelchek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                labelchekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(117, 117, 117))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(habitacion)
                                        .addGap(6, 6, 6))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addComponent(admin))))
                            .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel12)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_acompañantes)
                            .addComponent(reserva)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel11)))
                        .addGap(85, 85, 85)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(check_out)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(140, 140, 140))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(labelchek, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(147, 147, 147))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(252, 252, 252)
                .addComponent(jLabel10)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel10)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(reserva, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelchek, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(label_acompañantes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(habitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(check_out, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(admin)
                .addGap(18, 18, 18)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(65, 104, 163));

        jLabel7.setBackground(new java.awt.Color(51, 102, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/coral.png"))); // NOI18N
        jLabel7.setText("jLabel7");

        jLabel8.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText(" Bahia Coral");

        jLabel9.setFont(new java.awt.Font("Georgia", 3, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Hotel Resort ");

        check.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        check.setForeground(new java.awt.Color(255, 255, 255));
        check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/impuesto.png"))); // NOI18N
        check.setText("Check Out");
        check.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        check.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                checkMouseClicked(evt);
            }
        });

        jlabel_Salir.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jlabel_Salir.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cerrar-sesion.png"))); // NOI18N
        jlabel_Salir.setText("Salir");
        jlabel_Salir.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jlabel_Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_SalirMouseClicked(evt);
            }
        });

        acompa.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        acompa.setForeground(new java.awt.Color(255, 255, 255));
        acompa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/grupo (1).png"))); // NOI18N
        acompa.setText("Acompañantes");
        acompa.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        acompa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                acompaMouseClicked(evt);
            }
        });

        jlabel_Habi.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jlabel_Habi.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_Habi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/cama-matrimonial.png"))); // NOI18N
        jlabel_Habi.setText("Habitaciones");
        jlabel_Habi.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jlabel_Habi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_HabiMouseClicked(evt);
            }
        });

        jlabel_Reserva2.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jlabel_Reserva2.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_Reserva2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/reserva.png"))); // NOI18N
        jlabel_Reserva2.setText("Reservas");
        jlabel_Reserva2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jlabel_Reserva2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_Reserva2MouseClicked(evt);
            }
        });

        jlabel_Admin.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jlabel_Admin.setForeground(new java.awt.Color(255, 255, 255));
        jlabel_Admin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/administracion.png"))); // NOI18N
        jlabel_Admin.setText("Administración");
        jlabel_Admin.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jlabel_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlabel_AdminMouseClicked(evt);
            }
        });

        check_In.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        check_In.setForeground(new java.awt.Color(255, 255, 255));
        check_In.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/revisar.png"))); // NOI18N
        check_In.setText("Check In");
        check_In.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        check_In.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                check_InMouseClicked(evt);
            }
        });

        jLabel_Regis.setFont(new java.awt.Font("Georgia", 3, 12)); // NOI18N
        jLabel_Regis.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Regis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/nueva-cuenta (1).png"))); // NOI18N
        jLabel_Regis.setText("Registro Clientes");
        jLabel_Regis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel_Regis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RegisMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(check_In, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlabel_Reserva2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jlabel_Habi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlabel_Salir)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jLabel1))
                        .addComponent(acompa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jlabel_Admin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_Regis, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(check, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(jlabel_Reserva2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(check_In, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jlabel_Habi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jlabel_Admin)
                .addGap(34, 34, 34)
                .addComponent(jLabel_Regis, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(acompa, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlabel_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed

        pri = new Registro_Clientes();
        pri.setVisible(true);
        pri.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - pri.getSize().width) / 2;
        int y = (pantalla.height - pri.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        pri.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Registro Clientes");

    }//GEN-LAST:event_btn_clientesActionPerformed

    private void btn_clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_clientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_clientesMouseClicked

    private void reservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservaActionPerformed

        rsv1 = new Reserva();
        rsv1.setVisible(true);

        rsv1.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - rsv1.getSize().width) / 2;
        int y = (pantalla.height - rsv1.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        rsv1.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Reservas");
    }//GEN-LAST:event_reservaActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        lg = new Login();
        lg.setVisible(true);

        lg.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - lg.getSize().width) / 2;
        int y = (pantalla.height - lg.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        lg.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Reservas");

    }//GEN-LAST:event_adminActionPerformed

    private void habitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_habitacionActionPerformed
        // TODO add your handling code here:
        hab1 = new Habitaciones();  // Pasa null como idHabitacion
        hab1.setVisible(true);

        hab1.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - hab1.getSize().width) / 2;
        int y = (pantalla.height - hab1.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        hab1.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Habitaciones ");
    }//GEN-LAST:event_habitacionActionPerformed

    private void check_outActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_outActionPerformed
        // TODO add your handling code here:
        out = new check_out();  // Pasa null como idHabitacion
        out.setVisible(true);

        out.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - out.getSize().width) / 2;
        int y = (pantalla.height - out.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        out.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Check out ");
    }//GEN-LAST:event_check_outActionPerformed

    private void checkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_checkMouseClicked
        // TODO add your handling code here:}
        out = new check_out();  // Pasa null como idHabitacion
        out.setVisible(true);

        out.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - out.getSize().width) / 2;
        int y = (pantalla.height - out.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        out.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Check out ");

    }//GEN-LAST:event_checkMouseClicked

    private void jlabel_SalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_SalirMouseClicked
        // TODO add your handling code here:
        this.dispose(); // Cierra solo el JFrame actual

    }//GEN-LAST:event_jlabel_SalirMouseClicked

    private void acompaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_acompaMouseClicked
        // TODO add your handling code here:
        ac = new Acompañantes();
        ac.setVisible(true);

        ac.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - ac.getSize().width) / 2;
        int y = (pantalla.height - ac.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        ac.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Acompañantes");
    }//GEN-LAST:event_acompaMouseClicked

    private void jlabel_HabiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_HabiMouseClicked
        // TODO add your handling code here:
        hab1 = new Habitaciones();  // Pasa null como idHabitacion
        hab1.setVisible(true);

        hab1.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - hab1.getSize().width) / 2;
        int y = (pantalla.height - hab1.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        hab1.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Habitaciones ");
    }//GEN-LAST:event_jlabel_HabiMouseClicked

    private void jlabel_Reserva2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_Reserva2MouseClicked
        // TODO add your handling code here:

        rsv1 = new Reserva();
        rsv1.setVisible(true);

        rsv1.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - rsv1.getSize().width) / 2;
        int y = (pantalla.height - rsv1.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        rsv1.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Reservas");
    }//GEN-LAST:event_jlabel_Reserva2MouseClicked

    private void jlabel_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlabel_AdminMouseClicked
        // TODO add your handling code here:
        // TODO add your handling code here:
        lg = new Login();
        lg.setVisible(true);

        lg.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - lg.getSize().width) / 2;
        int y = (pantalla.height - lg.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        lg.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Reservas");
    }//GEN-LAST:event_jlabel_AdminMouseClicked

    private void label_acompañantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_label_acompañantesActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_label_acompañantesActionPerformed

    private void check_InMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_check_InMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        in = new check_in();
        in.setVisible(true);

        in.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - in.getSize().width) / 2;
        int y = (pantalla.height - in.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        in.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Check In");
    }//GEN-LAST:event_check_InMouseClicked

    private void jLabel_RegisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RegisMouseClicked
        // TODO add your handling code here:
          // TODO add your handling code here:
        pri = new Registro_Clientes();
        pri.setVisible(true);

        pri.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - pri.getSize().width) / 2;
        int y = (pantalla.height - pri.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        pri.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Registro Clientes");
                                       
    }//GEN-LAST:event_jLabel_RegisMouseClicked

    private void labelchekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_labelchekActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_labelchekActionPerformed

    private void label_acompañantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_label_acompañantesMouseClicked
        // TODO add your handling code here:
         // TODO add your handling code here:
        ac = new Acompañantes();
        ac.setVisible(true);

        ac.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - ac.getSize().width) / 2;
        int y = (pantalla.height - ac.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        ac.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Acompañantes");
    }//GEN-LAST:event_label_acompañantesMouseClicked

    private void labelchekMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_labelchekMouseClicked
        // TODO add your handling code here:
                in = new check_in();
        in.setVisible(true);

        in.setResizable(false);
        Dimension pantalla = Toolkit.getDefaultToolkit().getScreenSize();

        // Calcular la posición para centrar el JFrame
        int x = (pantalla.width - in.getSize().width) / 2;
        int y = (pantalla.height - in.getSize().height) / 2;

        // Posicionar la ventana en el centro de la pantalla
        in.setLocation(x, y);

        //Agregar Accion a Historial
        HistorialManager historial_acciones = HistorialManagerSingleton.getInstancia();
        historial_acciones.registrarAccion("Ingreso a Check In");
    }//GEN-LAST:event_labelchekMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel acompa;
    private javax.swing.JButton admin;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JLabel check;
    private javax.swing.JLabel check_In;
    private javax.swing.JButton check_out;
    private javax.swing.JButton habitacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Regis;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlabel_Admin;
    private javax.swing.JLabel jlabel_Habi;
    private javax.swing.JLabel jlabel_Reserva2;
    private javax.swing.JLabel jlabel_Salir;
    private javax.swing.JButton label_acompañantes;
    private javax.swing.JButton labelchek;
    private javax.swing.JButton reserva;
    // End of variables declaration//GEN-END:variables
}
